/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.camelia.example.lego;

import java.util.logging.Level;
import java.util.logging.Logger;
import serviceui.Printer;

/**
 *
 * @author camel
 */
public class LegoClientGUI extends javax.swing.JFrame implements Printer{

    private LegoClient client;
    
    public LegoClientGUI() {
        initComponents();
    }
    
    public LegoClientGUI(LegoClient aThis){
       this();
       this.client = aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        getBricks = new javax.swing.JButton();
        buildLego = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\camel\\Downloads\\lego-frame-3774083_640.png")); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setBounds(new java.awt.Rectangle(300, 300, 300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getBricks.setBackground(new java.awt.Color(0, 0, 0));
        getBricks.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        getBricks.setForeground(new java.awt.Color(0, 153, 51));
        getBricks.setText("Lego Sets");
        getBricks.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255))));
        getBricks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBricksActionPerformed(evt);
            }
        });
        getContentPane().add(getBricks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 40));

        buildLego.setBackground(new java.awt.Color(0, 0, 0));
        buildLego.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        buildLego.setForeground(new java.awt.Color(255, 0, 51));
        buildLego.setText("Build Lego");
        buildLego.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204))));
        buildLego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildLegoActionPerformed(evt);
            }
        });
        getContentPane().add(buildLego, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, 40));

        title.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title.setText("AI Lego Builder");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("*every parent's dream*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getBricksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBricksActionPerformed
        try {
            client.getLegoPiece();
        } catch (InterruptedException ex) {
            Logger.getLogger(LegoClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_getBricksActionPerformed

    private void buildLegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildLegoActionPerformed
        client.getBuildLego();
    }//GEN-LAST:event_buildLegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LegoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LegoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LegoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LegoClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LegoClientGUI().setVisible(true);
        });
    }
    
       // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration         
    public void append(String string) {
        jTextArea1.append("\n" + string);
    }

    public void clear() {
        jTextArea1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildLego;
    private javax.swing.JButton getBricks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
